services:
  - type: web
    name: analyzejd-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: analyzejd-db
          property: connectionString

databases:
  - name: analyzejd-db
    databaseName: analyzejd
    user: analyzejd
    plan: free
